{% set name = "rocm-cmake" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RadeonOpenCompute/rocm-cmake/archive/roc-{{ version }}.tar.gz
  sha256: c114f135593919ed7edce1b192ec4f66447815ca1f5e098bd5d210c006ab2cf1

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
  run:

test:
  commands:
    - test -f $PREFIX/share/rocm/cmake/ROCMConfig.cmake

about:
  home: https://github.com/RadeonOpenCompute/rocm-cmake
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Rocm cmake modules'

extra:
  recipe-maintainers:
    - isuruf
